### ISSUE TITLE
How to filter voucher used ?

### ISSUE THREAD

**Issue by songhanpoo** [songhanpoo/unifi#1]
Hi david
i have addon loop for generator multi-site but every run script i get all voucher, that include voucher used and not use. can you help me ?

**Comment by DJM0** [comment]
The `unifi_create_voucher` function will return all unused vouchers for a particular site which is what you should be seeing

**Comment by songhanpoo** [comment]
hi david !

because i'm only get new vouchers but your result get all voucher, that's include voucher not yet use

**Comment by DJM0** [comment]
Are you sure?

1. Can you try deleting **all** vouchers from your hotspot manager
2. Generate **one** using the script
3. Use the voucher
4. Run the script again to generate a second single voucher. This should only give you the new voucher, and not the expired one

**Comment by songhanpoo** [comment]
Hi david 
i'm sure. i think can filter voucher follow create time !
can you tell me about your rule ?
